### ISSUE TITLE
common data descriptor format (CDF)

### ISSUE THREAD

**Issue by geryxyz** [geryxyz/CodeMetropolis#19]

**Comment by blip24** [comment]
Design an XML-based format which can be used as the input of the mapping component. This will replace the graph files in mapping process. The goal is to make CDF suitable for general usage: instead of directly processing graph files, a common format will be described, and a converter (#35, #36) will take care of making a CDF of the graph.

**Comment by geryxyz** [comment]
property types:

- int 
- double
- string

no id on `element` tag
add `type` attribute to `element` tag
property recommendation: `source-id` type: string for id of the original/source element

**Comment by geryxyz** [comment]
`Elements` --> `element` as the project it-self
`name` attribute is human readable
all properties are optional
