### ISSUE TITLE
Updating the whole project to the latest stable Java version 

### ISSUE THREAD

**Issue by R3tes** [geryxyz/CodeMetropolis#368]
**General Overview**
We need to update our project to use the newest stable Java version. This means changing the Java version we use to run the project and fixing any issues that come up because of the change. We also need to make sure the main parts of our project still work well after the update.

**Tasks/Acceptance Criteria**
- **Switch to the New Java Version:** Start using the latest stable Java version for our project.
- **Update Java Version in Project Files:** Change the Java version in all our project's files, like `pom.xml`, to the new one.
- **Fix Any Problems:** Look for and fix any errors or issues that happen because of the new Java version. This might involve changing some files to make everything work right.
- **Test the Important Parts:** Test the main functions of our project (like converting, mapping, placing things, and showing results) manually to make sure they all work with the new Java version.

**Comment by Sibi09** [comment]
Differences between openJDK and oracleJDK:
Oracle JDK and OpenJDK are each a set of software and specifications known as Java Development Kits.  From Java 11 onward, Oracle JDK and OpenJDK are the same in build with the inclusion of features like Flight Recorder and Mission Control. Essentially, there are little to no code changes between Oracle JDK and OpenJDK, so they are functionally very similar. 

The biggest difference between OpenJDK and Oracle JDK is that OpenJDK is an open source project that is maintained by Oracle, Red Hat, and the community, whereas Oracle JDK is closed source, requires a paid license, and is maintained by Oracle. With that difference, there are a few features that aren’t available with OpenJDK due to the features being closed source or restricted by licensing.
[https://www.redhat.com/en/topics/application-modernization/openjdk-vs-oracle-jdk](url)
[https://www.educba.com/oracle-vs-openjdk/](url)
[https://xperti.io/blogs/openjdk-vs-oracle-jdk-differences/](url)
